version: '3.3'

services:
  wordpress:
    image: microsoft/multicontainerwordpress
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot:/var/www/html
      - #{CUSTOMID}#:/var/www/html/wp-content
    ports:
      - "8000:80"
    restart: always

    redis:
      image: redis:3-alpine
      restart: always