version: '3.3'

services:
  wordpress:
    image: microsoft/multicontainerwordpress
    volumes:
      - #{CUSTOMID}#:/var/www/html
    ports:
      - "8000:80"
    restart: always

    redis:
      image: redis:3-alpine
      restart: always

volumes:
  #{CUSTOMID}#: